export const CREATE_USER = 'CREATE_USER'
export const UPDATE_USER = 'UPDATE_USER'
export const DELETE_USER = 'DELETE_USER'
export const ALL_USER = 'ALL_USER'
export const HANDLE_CHANGE = 'HANDLE_CHANGE'
